version: '3.8'

services:
  # Frontend React - Solo el cliente
  bioelectron-frontend:
    image: node:20-alpine
    container_name: bioelectron-frontend
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3000:3000"  # Frontend React
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://190.117.90.92:5000
    command: >
      sh -c "
        apk add --no-cache git &&
        rm -rf /app/* /app/.* 2>/dev/null || true &&
        git clone https://github.com/tu-usuario/BioelectronCursosReact.git /tmp/repo &&
        cp -r /tmp/repo/* /app/ &&
        cp -r /tmp/repo/.* /app/ 2>/dev/null || true &&
        cd /app/client &&
        npm install -g copyfiles &&
        npm install &&
        npm run build &&
        npm install -g serve &&
        serve -s build -l 3000 -n
      "
    networks:
      - frontend-network

# Red para el frontend
networks:
  frontend-network:
    driver: bridge