version: '3.8'

services:
  # Aplicación Bioelectron Cursos
  bioelectron-app:
    image: node:18-alpine
    container_name: bioelectron-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3000:3000"  # Frontend React
      - "5000:5000"  # Backend API
    volumes:
      - uploads_data:/app/server/uploads
    environment:
      - MONGO_URI=mongodb://root:JOC3Xud4AIVGacb@190.117.90.92:27017/admin
      - PORT=5000
      - JWT_SECRET=secretkey
      - NODE_ENV=production
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/tu-usuario/BioelectronCursosReact.git . &&
        cd server && npm install &&
        cd ../client && npm install &&
        npm run build &&
        npm install -g serve &&
        cd ../server && node index.js &
        cd ../client && serve -s build -l 3000 &
        wait
      "
    networks:
      - bioelectron-network

# Volúmenes para persistencia de archivos subidos
volumes:
  uploads_data:
    driver: local

# Red para comunicación interna
networks:
  bioelectron-network:
    driver: bridge